# Generated by Django 6.0.2 on 2026-02-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_payment_method_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
