# Generated by Django 6.0.2 on 2026-02-27 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orderitem_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product_image',
        ),
    ]
